[package]
name = "feedback"
version = "0.1.0"
authors = ["Noah Weninger <nweninge@ualberta.ca>"]

[dependencies]
ladspa = "*"
mio = "0.4.4"
time = "0.1.34"
rustc-serialize = "0.3.16"
rmp-serialize = "*"

[lib]
name = "feedback"
crate-type = ["dylib"]
